apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: babyapp
spec:
  ingressClassName: nginx
  rules:
  - host: babyapp-prod.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: babyapp
            port:
              number: 80
