apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: babyapp
spec:
  template:
    spec:
      containers:
        - name: babyapp
          image: babyapp:v3
          imagePullPolicy: IfNotPresent
          env:
            - name: APP_VERSION
              value: "v3"


          

