apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: babyapp
  namespace: staging
spec:
  rules:
    - host: babyapp.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: babyapp
                port:
                  number: 80

