apiVersion: apps/v1
kind: Deployment
metadata:
  name: babyapp
  namespace: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: babyapp
  template:
    metadata:
      labels:
        app: babyapp
    spec:
      containers:
        - name: babyapp
          image: babyapp:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5

